project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Hanan Ather"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: My Writing
      - href: principles.qmd
        text: My Principles

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    toc: false

execute:
  freeze: auto
